---
driver:
  name: vagrant
  require_chef_omnibus: 12.15.19
  synced_folders:
    - ["test/fixtures/config", "/tmp/config"]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: chef
    run_list:
      - recipe[chef::_kitchen]
      - recipe[chef::server]
    driver:
      customize:
        memory: 1024
      network:
        - ['private_network', {ip: '192.168.254.10'}]
  - name: automate
    run_list:
      - recipe[chef::_kitchen]
      - recipe[chef::automate]
    driver:
      customize:
        memory: 1024
      network:
        - ['private_network', {ip: '192.168.254.20'}]
  - name: build01
    run_list:
      - recipe[chef::_kitchen]
      - recipe[chef::build_node_v2]
    attributes:
    driver:
      network:
        - ['private_network', {ip: '192.168.254.21'}]
  - name: build02
    run_list:
      - recipe[chef::_kitchen]
      - recipe[chef::build_node_v1]
    attributes:
    driver:
      network:
        - ['private_network', {ip: '192.168.254.22'}]
  - name: supermarket
    run_list:
      - recipe[chef::_kitchen]
      - recipe[chef::supermarket]
    driver:
      network:
        - ['private_network', {ip: '192.168.254.30'}]
