---
driver:
  name: vagrant
  # require_chef_omnibus: 12.15.19
  synced_folders:
    - ["test/fixtures/config", "/tmp/config"]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: chef
    run_list:
      - recipe[chef_stack::_kitchen]
      - recipe[chef_stack::server]
    driver:
      customize:
        memory: 1024
      network:
        - ['private_network', {ip: '192.168.254.10'}]
  # - name: chefbe
  #   run_list:
  #     - recipe[chef_stack::_kitchen]
  #     - recipe[chef_stack::backend]
  #   driver:
  #     customize:
  #       memory: 1024
  #     network:
  #       - ['private_network', {ip: '192.168.254.11'}]
  - name: automate
    run_list:
      - recipe[chef_stack::_kitchen]
      - recipe[chef_stack::automate]
    driver:
      customize:
        memory: 1024
      network:
        - ['private_network', {ip: '192.168.254.20'}]
  - name: buildv1
    run_list:
      - recipe[chef_stack::_kitchen]
      - recipe[chef_stack::build_node_v1]
    attributes:
    driver:
      network:
        - ['private_network', {ip: '192.168.254.21'}]
  - name: buildv2
    run_list:
      - recipe[chef_stack::_kitchen]
      - recipe[chef_stack::build_node_v2]
    attributes:
    driver:
      network:
        - ['private_network', {ip: '192.168.254.22'}]
  - name: supermarket
    run_list:
      - recipe[chef_stack::_kitchen]
      - recipe[chef_stack::supermarket]
    driver:
      network:
        - ['private_network', {ip: '192.168.254.30'}]
